name: Input Simulator
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: click_data_raw
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
