name: Input Simulator
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: click_data_raw
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
